# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_applicant_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
