# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
