# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_auto_20200123_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
